# Generated by Django 5.2.4 on 2025-07-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='audio_url',
        ),
        migrations.AddField(
            model_name='track',
            name='audio_file',
            field=models.FileField(default='', upload_to='tracks/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='track',
            name='lyrics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
